import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" data-theme="nord">
			<body className={inter.className}>
				<main className="flex items-center justify-center flex-col gap-2 bg-base-100 min-h-screen p-4">
					{children}
				</main>
			</body>
		</html>
	);
}
